apiVersion: "cilium.io/v2"
kind: CiliumNetworkPolicy
metadata:
  name: "all"
  namespace: "dev"
spec:
  endpointSelector:
    matchLabels:
      role: db
  ingress:
  - fromEndpoints:
    - {}
  egress:
  - toEndpoints:
    - {}