apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: "my-policy"
spec:
  endpointSelector:
    matchLabels:
      role: warehouse
  egress:
  - toEndpoints:
    - matchLabels:
       "k8s:io.kubernetes.pod.namespace": kube-system
       "k8s:k8s-app": kube-dns
    toPorts:
      - ports:
         - port: "53"
           protocol: ANY
        rules:
          dns:
            - matchName: "cilium.io"
            - matchPattern: "*.cilium.io"
            - matchPattern: "*.api.cilium.io"

  - toFQDNs:
      - matchName: "kodekloud.com"
      - matchName: "app.kodekloud.com"
      - matchName: "api.kodekloud.com"