apiVersion: "cilium.io/v2"
kind: CiliumNetworkPolicy
metadata:
  name: "my-policy"
  namespace: "prod"
spec:
  endpointSelector:
    matchLabels:
      role: products
  ingress:
    - fromEntities:
      - world